# Generated by Django 4.0 on 2022-02-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer_task',
            name='submitdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
